### PR TITLE
Fix :recheck conditions when creating and editing activity

### LINKED ISSUE #302: recheck conditions when creating and editing activity
- [ ] All the fields should have very precise conditions

- [ ] enable the button once all the fields have been filled

### PR DESCRIPTION
**Pull request by hmaryam84**
#### **Summary**
This PR introduces stricter and clearer conditions for enabling the "Create" and "Edit" buttons on the activity creation and editing screens. These changes ensure all required fields are properly filled and validated, improving user experience and data integrity.

---

#### **Changes**

1. **Fix: Enhanced Validation for Create Button**
   - Added checks to ensure all fields are completed before enabling the "Create" button:
     - **Mandatory Fields**: Title, description, price, number of places, and location.
     - **Selections**: A type and category must be chosen.
     - **Timing**: A date, start time, and end time must be selected.

2. **Fix: Title and Description Length Validation**
   - Added the following restrictions:
     - Title length: Maximum of 50 characters.
     - Description length: Maximum of 500 characters.
   - Implemented a live counter to display the remaining characters, providing users with a clear indicator of how much text space is left.

3. **Fix: Enhanced Validation for Edit Button**
   - Applied the same conditions as for the "Create" button to the "Edit" screen:
     - All fields must be filled before enabling the button.
     - Title and description length limits with remaining character indicators.

4. **Refactor: Composable for Reusable Code**
   - Consolidated shared logic for title and description validation into a reusable composable, reducing code duplication and improving maintainability.

5. **Testing: Add and Update Test Cases**
   - **New Tests**:
     - Verified that the "Create" and "Edit" buttons are disabled when required fields are empty or conditions are unmet.
     - Confirmed the correct display of the remaining character counter for both title and description fields.
   - **Updated Tests**:
     - Adapted existing tests to account for the new conditions and validation logic.

---

#### **Testing**
- **UI Tests**:
  - Validated that buttons remain disabled until all required conditions are met.
  - Tested the live character counter for accurate updates as users type.
- **Unit Tests**:
  - Checked the correct behavior of the reusable composable for field validation.
- **Integration Tests**:
  - Ensured seamless integration of the new validation logic in both create and edit screens.

---

#### **Screenshots**
image

! I think there is an issue with the location ...

Let me know if additional details are needed!

close #302

### CODE REVIEW

File: app/src/main/java/com/android/sample/ui/activity/CreateActivity.kt [hunk 1]
```diff
@@ -503,7 +516,17 @@ fun CreateActivityScreen(
...
+                      title.isNotEmpty() &&
+                          description.isNotEmpty() &&
+                          price.isNotEmpty() &&
+                          placesMax.isNotEmpty() &&
+                          selectedLocation != null &&
+                          selectedOptionType != "Select a type" &&
+                          selectedOptionCategory != "Select a category" &&
+                          startTime.isNotEmpty() &&
+                          duration.isNotEmpty() &&
+                          dueDate.toDate().after(Timestamp.now().toDate()),
```
Comment (aminebenji04) [inline app/src/main/java/com/android/sample/ui/activity/CreateActivity.kt:529]: very good, these missing conditions were painful because it was not very coherent when adding/editing

File: app/src/main/java/com/android/sample/ui/activity/CreateActivity.kt [hunk 2]
```diff
@@ -601,3 +624,30 @@ fun CreateActivityScreen(
...
+                  progress = field.length / maxLength.toFloat(),
+                  modifier =
+                      Modifier.height(STANDARD_PADDING.dp)
+                          .width(130.dp)
+                          .clip(RoundedCornerShape(SMALL_PADDING.dp))
+                          .testTag("remainingPlaceProgress"),
+                  color = Color(DARK_BLUE_COLOR),
+                  backgroundColor = Color.LightGray)
+            }
+      }
```
Comment (aminebenji04) [inline app/src/main/java/com/android/sample/ui/activity/CreateActivity.kt:652]: Good UI improvement that will make it easier for the user to see which activities are the most close to be filled

File: app/src/main/java/com/android/sample/ui/activity/EditActivity.kt [hunk 3]
```diff
@@ -505,7 +508,15 @@ fun EditActivityScreen(
...
-                enabled = title.isNotEmpty() && description.isNotEmpty(),
+                enabled =
+                    title.isNotEmpty() &&
+                        description.isNotEmpty() &&
+                        price.isNotEmpty() &&
+                        maxPlaces.isNotEmpty() &&
+                        selectedOptionType != "Select a type" &&
+                        selectedOptionCategory != "Select a category" &&
+                        startTime?.isNotEmpty() ?: false &&
+                        duration.isNotEmpty(),
```
Comment (aminebenji04) [inline app/src/main/java/com/android/sample/ui/activity/EditActivity.kt:519]: Same logic as in create activity, very good

File: app/src/androidTest/java/com/android/sample/ui/activity/CreateActivityScreenTest.kt
Comment (aminebenji04) [inline app/src/androidTest/java/com/android/sample/ui/activity/CreateActivityScreenTest.kt:1]: Ok you updated the tests according to the new conditions, this is good and it will also increase code coverage

**Review by aminebenji04 — APPROVED** [review]
This is a very good PR. It is very understandable thanks to the number of commits and also it isn't risky as it doesn't touch chore features. If the tests pass and the CI also, then we can be sure our app stays functionnal
